# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6241bb5e1ec41565d31a8f4254b67e2e063524ac3e9ae97f84321af6bb0845315e8dc1164e2ee2de204602b3778cb54caba21d8da315e3eeca27a30dd60e4f03

test:
  secret_key_base: c594b42661aef330522dbaeaab4ae5fbe63e0ec099cbefe4b22b918b5ab4f736d35cc04ed7404d787e6d26ac615e4a77bc2a64fd53c802c8d175194a8d00e203

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
